export const allRequests = [
  {
    status: "Pending",
    requestedTime: "March 10, 2025, 08:30 AM",
    acknowledgedTime: "March 10, 2025, 10:15 AM",
    completedTime: null,
    purpose: "For school research project",
    dateNeeded: "March 15, 2025",
    program: "Agricultural Studies",
    materials: [
      {
        name: "Fisheries Guide Book",
        quantity: 10,
        type: "Book",
        bannerPrograms: ["Livestock", "Poultry", "Agriculture"],
        image: "/broiler.jpg",
        views: 120,
        downloadCount: 45,
      },
    ],
  },
  {
    status: "Completed",
    requestedTime: "March 8, 2025, 09:00 AM",
    acknowledgedTime: "March 8, 2025, 11:30 AM",
    completedTime: "March 9, 2025, 02:00 PM",
    purpose: "Community livelihood training",
    dateNeeded: "March 12, 2025",
    program: "Farmers’ Assistance Program",
    materials: [
      {
        name: "Corn Farming Manual",
        quantity: 7,
        type: "Manual",
        bannerPrograms: ["Corn"],
        image: "/ngulay.jpg",
        views: 200,
        downloadCount: 78,
      },
      {
        name: "Livestock Booklet",
        quantity: 12,
        type: "Booklet",
        bannerPrograms: ["Livestock", "Poultry", "Farm"],
        image: "/isda.jpg",
        views: 350,
        downloadCount: 120,
      },
      {
        name: "Rice Farming Handbook",
        quantity: 18,
        type: "Coffee Table Book",
        bannerPrograms: ["Rice"],
        image: "/vege.jpg",
        views: 280,
        downloadCount: 95,
      },
    ],
  },
];

export const allMaterials = [
  {
    name: "Fisheries Guide Book",
    quantity: 10,
    type: "Book",
    bannerPrograms: ["Livestock", "Poultry", "Agriculture"],
    image: "/broiler.jpg",
    views: 120,
    downloadCount: 45,
  },
  {
    name: "Corn Farming Manual",
    quantity: 7,
    type: "Manual",
    bannerPrograms: ["Corn"],
    image: "/ngulay.jpg",
    views: 200,
    downloadCount: 78,
  },
  {
    name: "Livestock Booklet",
    quantity: 12,
    type: "Booklet",
    bannerPrograms: ["Livestock", "Poultry", "Farm"],
    image: "/isda.jpg",
    views: 350,
    downloadCount: 120,
  },
  {
    name: "Rice Farming Handbook",
    quantity: 18,
    type: "Coffee Table Book",
    bannerPrograms: ["Rice"],
    image: "https://scontent.fmnl17-1.fna.fbcdn.net/v/t1.15752-9/433884370_791061999576137_5594001860413791526_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=0024fc&_nc_ohc=iqz9ph-sYJkQ7kNvgGAZZN0&_nc_oc=AdieVZmEdryZpPClZPbFOo5zlcb8hIPgqDshSTB7ggI-vuX7mdhWuYL3xaMgwmizpCs&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=scontent.fmnl17-1.fna&oh=03_Q7cD1wEabxRpfcn0UM8AtFJ--48BDolPoKFimPULadrc19gMVg&oe=67FF3C79",
    views: 280,
    downloadCount: 95,
  },
  {
    name: "Rice Farming Handbook",
    quantity: 18,
    type: "Coffee Table Book",
    bannerPrograms: ["Rice"],
    image: "https://files.magzter.com/resize/magazine/1403149542/1570239156/view/3.jpg",
    views: 280,
    downloadCount: 95,
  },
  {
    name: "Leeeeebrrrrrroooooooonnnnnnnn",
    quantity: 18,
    type: "Coffee Table Book",
    bannerPrograms: ["Rice"],
    image: "https://render.fineartamerica.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/2/22-lebron-james-jesse-d-garrabrant.jpg",
    views: 280,
    downloadCount: 95,
  },
];